chain=elementsregtest
rpcuser=user1
rpcpassword=password1
server=1
listen=1
txindex=1
validatepegin=1
mainchainrpchost=bitcoind
mainchainrpcport=18888
mainchainrpcuser=user3
mainchainrpcpassword=password3
initialfreecoins=2100000000000000
fallbackfee=0.0002
[elementsregtest]
rpcport=18884
port=18886
anyonecanspendaremine=1
connect=elementsd2:18887
