chain=liquidtestnet
rpcuser=user2
rpcpassword=password2
server=1
listen=1
txindex=1
fallbackfee=0.00001
[liquidtestnet]
rpcport=18885
port=18887
rpcbind=0.0.0.0
rpcallowip=0.0.0.0/0
addnode=liquid.network:18844
addnode=liquid-testnet.blockstream.com:18891
addnode=liquidtestnet.com:18891
