chain=elementsregtest
rpcuser=user2
rpcpassword=password2
server=1
listen=1
txindex=1
mainchainrpchost=bitcoind
mainchainrpcport=18888
mainchainrpcuser=user3
mainchainrpcpassword=password3
initialfreecoins=2100000000000000
fallbackfee=0.0002
[elementsregtest]
rpcport=18885
port=18887
anyonecanspendaremine=1
connect=elementsd1:18886
